version: '2.1'
services:
     elasticsearch:
       image: elasticsearch:1.7.6
       container_name: elasticsearch
       ports:
             - "9200:9200"
             - "9300:9300"
       networks:
           - docker-elk

     kibana:
       image: kibana:4.1.3
       container_name: kibana
       ports:
             - "5601:5601"
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
          - docker-elk
       depends_on:
          - elasticsearch

networks:
  docker-elk:
    driver: bridge
